[package]
name = "isin"
version = "0.1.1"
description = "Support for creating and validating ISINs"
authors = ["Gregor Purdy <gregor@abcelo.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
keywords = ["isin", "identifier", "finance", "equity", "stock"]
readme = "README.md"
repository = "https://github.com/gnp/isin-rs.git"

[dependencies]
