name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Clippy
      run: cargo clippy --all-targets --all-features
    - name: Check Format
      run: cargo fmt --all --check
